### ISSUE TITLE
Build fresh project per run

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/solutions-modern-cicd-anthos#68]
In order to improve the reliability of CI (#63) we should try running the solution on a fresh project each time.

**Comment by bgood** [comment]
Looks like the most recent test failed because of a quota issue.

Step #4 - "trigger-clusters": Error: Error waiting for creating GKE NodePool: Insufficient quota to satisfy the request: Not all instances running in IGM after 20.640815354s. Expect 1. Current errors: [GCE_QUOTA_EXCEEDED]: Instance 'gke-dev-us-central1-wi-pool-98d72843-0nsx' creation failed: Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 8.0 in region us-central1.

**Comment by morgante** [comment]
Could we use smaller clusters?

**Comment by bgood** [comment]
I think we have 3 options:

1. The CPU and memory requests are pretty close to the limit of our current sizing, so we could use fewer nodes, but would have to make them bigger.

1. We could move some clusters to other regions, that would should get us inside the quota.
Dev - us-west1
Staging - us-west2

1. Use private clusters

**Comment by morgante** [comment]
Using different regions sounds like a good fix.

**Comment by bgood** [comment]
PR #86 submitted to move the dev and staging clusters.

**Comment by bgood** [comment]
Still have tests failing but we are now running tests in new and clean projects for each CI execution.
